name: Check Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '38 8 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  check-deps:
    name: Check Dependencies
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        otp_version: ['27.1']

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          rebar3-version: '3.22.1'
          version-type: 'strict'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/rebar3
            _build
          key: ${{ runner.os }}-erlang-${{ matrix.otp_version }}-${{ hashFiles('**/*rebar.lock') }}

      - name: Build
        run: make build

      - name: Check dependencies
        run: .github/workflows/check-deps.sh
        env:
          BRANCH_NAME: update-deps-${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
